# Generated by Django 4.2.25 on 2025-10-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_unique_number', models.CharField(db_index=True, max_length=64)),
                ('contract_number', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('buyer_name', models.CharField(db_index=True, max_length=255)),
                ('buyer_eik', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('seller_name', models.CharField(db_index=True, max_length=255)),
                ('seller_eik', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('notice_type', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('lot_identifier', models.CharField(blank=True, default='', max_length=128)),
                ('notice_published_at', models.DateField(blank=True, null=True)),
                ('contract_signed_at', models.DateField(blank=True, db_index=True, null=True)),
                ('annex_published_at', models.DateField(blank=True, null=True)),
                ('year_signed', models.IntegerField(blank=True, db_index=True, null=True)),
                ('contract_subject', models.TextField(blank=True, default='')),
                ('contract_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('contract_currency', models.CharField(blank=True, default='', max_length=8)),
                ('contract_value_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('current_currency', models.CharField(blank=True, default='', max_length=8)),
                ('current_value_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('annex_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('annex_currency', models.CharField(blank=True, default='', max_length=8)),
                ('annex_value_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('change_of_value_desc', models.TextField(blank=True, default='')),
                ('change_reason', models.TextField(blank=True, default='')),
                ('is_group_of_economic_operators', models.BooleanField(default=False)),
                ('subcontractor_name', models.CharField(blank=True, default='', max_length=255)),
                ('subcontractor_eik', models.CharField(blank=True, default='', max_length=32)),
                ('features', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'indexes': [models.Index(fields=['buyer_eik'], name='analytics_c_buyer_e_6b54c0_idx'), models.Index(fields=['seller_eik'], name='analytics_c_seller__52fe06_idx'), models.Index(fields=['notice_type'], name='analytics_c_notice__b47af0_idx'), models.Index(fields=['contract_signed_at'], name='analytics_c_contrac_11b627_idx'), models.Index(fields=['year_signed'], name='analytics_c_year_si_827d55_idx')],
            },
        ),
    ]
